version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.0.2
  - dependency-name: azure-pipelines-task-lib
    versions:
    - 3.1.1
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: webpack
    versions:
    - 5.35.0
