# pull_request_rules:
#   - name: automatic merge for Dependabot pull requests
#     conditions:
#       - author~=^dependabot(|-preview)\[bot\]$
#       - check-success=azure-devops-mutationreport-publisher
#       - title~=Bump [^\s]+ from ([\d]+)\..+ to \1\.
#       - base=master
#       - label=dependencies
#     actions:
#       merge:
#         method: squash
